name: Build & Deploy WebApp

env:
  AWS_REGION: us-east-1

on:
  push:
    branches: [ main ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: |
        mkdir lambda_package
        echo "${{ env.ARTIFACT_NAME }}"
        pwd
        ls
        mvn -B clean package --file pom.xml
        pwd
        cd target
        ls -al
        cd ..
        mv ./target/serverless-0.0.1-SNAPSHOT.jar ./lambda_package/serverless-1.jar
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy Artifact to S3
      run: |
        aws s3 sync ./lambda_package s3://${{ secrets.S3_LAMBDA_BUCKET_PROD }}

    - name: deploy
      run: |
        aws lambda update-function-code --function-name=send_email --s3-bucket=prod.lambda --s3-key=serverless-1.jar
        
